name: Daily Curl Request

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-curl:
    runs-on: ubuntu-latest

    steps:
      - name: Run Curl Request
        run: curl https://nest-admin-093x.onrender.com
