name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd ${{ secrets.REMOTE_WORKDIR }}
            git reset --hard origin/main
            git pull

            VERSION=$(date +%Y%m%d%H%M%S)

            echo "Cleaning up unused docker objects..."
            docker system prune -af

            echo "Building docker image..."
            docker build -t shangdingziben/shangdingziben-app:$VERSION .

            echo "Stopping existing container if any..."
            docker stop shangdingziben-app || true
            docker rm shangdingziben-app || true

            echo "Starting new container..."
            docker run -d -p 7001:7001 --name shangdingziben-app shangdingziben/shangdingziben-app:$VERSION
