name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd ${{ secrets.REMOTE_WORKDIR }}
            git reset --hard origin/main
            git pull

            VERSION=$(date +%Y%m%d%H%M%S)

            docker build -t shangdingziben/shangdingziben-app:$VERSION .
            docker stop shangdingziben-app || true
            docker rm shangdingziben-app || true
            docker run -d -p 7001:7001 --name shangdingziben-app shangdingziben/shangdingziben-app:$VERSION
